name: Generar APK Android

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Construir APK
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar Dependencias
        run: npm install

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permisos de ejecución a Gradle
        working-directory: ./android
        run: chmod +x gradlew

      - name: Compilar APK
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Subir APK final
        uses: actions/upload-artifact@v4
        with:
          name: Simulador_TSJE_APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
